import { isDNS1123Subdomain } from '../../k8s/names.js';
import { isCronSchedule } from '../../k8s/cron.js';
import { didYouMean } from '../suggest.js';
import type { Path } from '../types.js';
import {
  asBoolean,
  asNumber,
  asObject,
  asString,
  type Rule,
  type RuleContext,
} from './context.js';
import { checkKeyedMap } from './metadata.js';
import { checkJobSpec } from './job.js';

const CRONJOB_DOCS = 'https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/';

/**
 * The CronJob controller appends "-<unix-timestamp>", 11 characters, to this
 * name to make each run's Job name, and a Job name has to fit in the
 * 63-character DNS label limit a Pod hostname allows. DNS1035LabelMaxLength(63)
 * - 11, from ValidateCronJobCreate in pkg/apis/batch/validation. Upstream skips
 * this check on update, to let an already-too-long CronJob still be edited or
 * deleted; a linter has no such distinction to make.
 */
const CRONJOB_NAME_MAX = 52;

/**
 * https://data.iana.org/time-zones/theory.html#naming — the character class
 * validateTimeZone checks each "/"-separated component of `timeZone` against,
 * from pkg/apis/batch/validation.
 */
const TIME_ZONE_COMPONENT = /^[A-Za-z.\-_0-9+]{1,14}$/;

/**
 * The checks the apiserver runs on a CronJob, from ValidateCronJobCreate /
 * validateCronJobSpec in pkg/apis/batch/validation. A CronJob is namespaced
 * like any other kind, so `nameFormat`/`clusterScoped` in kinds.ts need
 * nothing special — only the extra 52-character cap below, which is this
 * module's to report since it has no home in `nameFormat`.
 *
 * `spec.jobTemplate.spec` is a full JobSpec, and upstream validates it with
 * the very same `validateJobSpec` a Job's own spec goes through — so this
 * module does not re-derive those ~500 lines of checks under `cronjob/*`
 * ids. `checkJobSpec`, exported from `job.ts` for exactly this, is called
 * against the nested spec and reports under the `job/*` ids a Job would use
 * for the same problem, at the deeper path. Only the two checks that read the
 * *object's* own name or selector rather than anything inside the JobSpec —
 * a Job's generated-selector check and its indexed-Pod-hostname check — stay
 * out of `checkJobSpec`, and neither applies here: a CronJob's Job name is
 * generated by the controller, not written in the manifest, and its
 * jobTemplate may not carry a selector at all (checked below).
 *
 * `concurrencyPolicy` needs no rule of its own: nothing else here turns on
 * it, and both an unknown value and the empty string the apiserver also
 * rejects are already `enum/invalid-value`, transcribed in enums.ts. Nothing
 * in a CronJob is version-gated — CronJobSpec, timeZone included, has been
 * unchanged from the 1.25 floor through 1.36.
 */
export const cronJobRule: Rule = {
  id: 'cronjob/spec',
  run(ctx: RuleContext) {
    // An absent spec is a CronJob naming no schedule, the same rejection as
    // an empty one. A spec of the wrong shape is layer 1's to report.
    const declared = ctx.doc['spec'];
    const spec = declared == null ? {} : asObject(declared);
    if (!spec) return;

    checkSchedule(ctx, spec);
    checkTimeZone(ctx, spec);
    checkStartingDeadline(ctx, spec);
    checkHistoryLimits(ctx, spec);
    checkNameLength(ctx);

    const jobTemplate = asObject(spec['jobTemplate']);
    if (!jobTemplate) return;

    const templateMetadata = asObject(jobTemplate['metadata']);
    if (templateMetadata) {
      checkKeyedMap(
        ctx,
        templateMetadata['labels'],
        ['spec', 'jobTemplate', 'metadata', 'labels'],
        'label',
        true,
      );
      checkKeyedMap(
        ctx,
        templateMetadata['annotations'],
        ['spec', 'jobTemplate', 'metadata', 'annotations'],
        'annotation',
        false,
      );
    }

    const jobSpec = asObject(jobTemplate['spec']);
    if (!jobSpec) return;

    checkJobTemplateSelector(ctx, jobSpec);
    checkJobSpec(ctx, jobSpec, ['spec', 'jobTemplate', 'spec']);
  },
};

/* Schedule */

function checkSchedule(ctx: RuleContext, spec: Record<string, unknown>): void {
  const declared = spec['schedule'];

  // schedule is required by the schema, so an absent or null value — a key
  // written with no value decodes to null — is already schema/required-field's
  // report. An empty string is a value, not an absence, so it passes that
  // check; this is the one shape only this rule catches.
  if (declared === '') {
    ctx.report({
      ruleId: 'cronjob/missing-schedule',
      severity: 'error',
      path: ['spec', 'schedule'],
      message: 'A CronJob must set spec.schedule.',
      explanation:
        'The schedule is what makes this a CronJob rather than a Job: without it there is nothing to say when a Job should be created, and the apiserver rejects the object with "Required value".',
      docsUrl: CRONJOB_DOCS,
    });
    return;
  }

  const schedule = asString(declared);
  if (schedule === undefined) return; // absent, wrong type, or already reported above

  // robfig/cron, the library the schedule is parsed with, reads a leading
  // "TZ=<zone> " or "CRON_TZ=<zone> " as the schedule's own time zone — but
  // CronJobSpec carries a dedicated timeZone field for exactly that, and the
  // apiserver rejects the prefix outright so a schedule has one place, not
  // two, to say what zone it runs in. (Upstream still tolerates the prefix on
  // an *update* that does not touch a schedule which already had one, to
  // avoid breaking an existing CronJob; a linter sees one snapshot, not an
  // old and a new one, so it always reports it.)
  if (schedule.includes('TZ')) {
    ctx.report({
      ruleId: 'cronjob/timezone-in-schedule',
      severity: 'error',
      path: ['spec', 'schedule'],
      message: 'schedule must not carry a "TZ=" or "CRON_TZ=" prefix; use spec.timeZone instead.',
      explanation:
        'The apiserver rejects the combination with "cannot use TZ or CRON_TZ in schedule, use timeZone field instead" — or, if spec.timeZone is also set, "cannot use both timeZone field and TZ or CRON_TZ in schedule".',
      docsUrl: CRONJOB_DOCS,
    });
    return;
  }

  const check = isCronSchedule(schedule);
  if (!check.ok) {
    ctx.report({
      ruleId: 'cronjob/invalid-schedule',
      severity: 'error',
      path: ['spec', 'schedule'],
      message: `"${schedule}" is not a valid cron schedule: it ${check.reason}.`,
      explanation:
        'The schedule is five whitespace-separated fields — minute, hour, day of month, month, day of week — each a "*", a number, a range, a step or a comma-separated list of those, or one of the descriptors "@yearly", "@monthly", "@weekly", "@daily", "@hourly" and "@every <duration>".',
      docsUrl: CRONJOB_DOCS,
    });
  }
}

/* Time zone */

function checkTimeZone(ctx: RuleContext, spec: Record<string, unknown>): void {
  const declared = spec['timeZone'];
  if (declared === undefined) return;
  const timeZone = asString(declared);
  if (timeZone === undefined) return; // wrong type; layer 1's report

  const path: Path = ['spec', 'timeZone'];

  if (timeZone === '') {
    ctx.report({
      ruleId: 'cronjob/invalid-time-zone',
      severity: 'error',
      path,
      message: 'timeZone must not be an empty string; leave the field out to use the default zone.',
      explanation:
        'An absent timeZone runs the schedule in the kube-controller-manager process\'s own zone, which is what an empty string would otherwise be mistaken for — the apiserver rejects the empty string rather than treat it the same as leaving the field out.',
      docsUrl: CRONJOB_DOCS,
    });
    return;
  }

  for (const part of timeZone.split('/')) {
    if (part === '.' || part === '..' || part.startsWith('-') || !TIME_ZONE_COMPONENT.test(part)) {
      ctx.report({
        ruleId: 'cronjob/invalid-time-zone',
        severity: 'error',
        path,
        message: `"${timeZone}" is not a valid time zone name.`,
        explanation:
          'Each "/"-separated part of an IANA time zone name is at most 14 characters of ASCII letters, digits, ".", "-" or "_", must not start with "-", and must not be "." or "..".',
        docsUrl: CRONJOB_DOCS,
      });
      return;
    }
  }

  if (timeZone.toLowerCase() === 'local') {
    ctx.report({
      ruleId: 'cronjob/invalid-time-zone',
      severity: 'error',
      path,
      message: '"Local" is not an explicit time zone.',
      explanation:
        'timeZone has to name a zone from the IANA database, such as "America/New_York" — the apiserver rejects "Local" because what it means depends on the host it happens to run on.',
      docsUrl: CRONJOB_DOCS,
    });
    return;
  }

  if (isKnownTimeZone(timeZone)) return;

  const suggestion = didYouMean(timeZone, supportedTimeZones());
  ctx.report({
    ruleId: 'cronjob/unknown-time-zone',
    severity: 'error',
    path,
    message: suggestion
      ? `"${timeZone}" is not a known time zone. Did you mean "${suggestion}"?`
      : `"${timeZone}" is not a known time zone.`,
    explanation:
      'The apiserver loads the zone from the system-wide IANA time zone database during validation, so a well-formed but unlisted name — a typo, or a name the database has renamed — is rejected the same as a malformed one.',
    docsUrl: CRONJOB_DOCS,
    fix: suggestion
      ? { title: `Change to "${suggestion}"`, safe: true, ops: [{ op: 'set', path, value: suggestion }] }
      : undefined,
  });
}

/**
 * The browser (and Node) stand-in for Go's `time.LoadLocation`: the runtime's
 * own ICU time zone database, which is what actually decides how the schedule
 * runs, not just whether the name is well-formed.
 */
function isKnownTimeZone(timeZone: string): boolean {
  try {
    // Constructing it is the check: it throws a RangeError for a zone the
    // ICU database does not know.
    void new Intl.DateTimeFormat('en-US', { timeZone });
    return true;
  } catch {
    return false;
  }
}

function supportedTimeZones(): string[] {
  try {
    return Intl.supportedValuesOf('timeZone');
  } catch {
    // Older runtimes lack supportedValuesOf; there is simply no suggestion.
    return [];
  }
}

/* Deadlines and history */

function checkStartingDeadline(ctx: RuleContext, spec: Record<string, unknown>): void {
  const value = asNumber(spec['startingDeadlineSeconds']);
  if (value === undefined || value >= 0) return;
  ctx.report({
    ruleId: 'cronjob/negative-starting-deadline',
    severity: 'error',
    path: ['spec', 'startingDeadlineSeconds'],
    message: `startingDeadlineSeconds must not be negative, but is ${value}.`,
    explanation:
      'It is how many seconds past the scheduled time a run may still be started; a run that misses even that deadline counts as failed.',
    docsUrl: CRONJOB_DOCS,
  });
}

const HISTORY_LIMIT_FIELDS = [
  ['successfulJobsHistoryLimit', 'how many successful Jobs are kept around'],
  ['failedJobsHistoryLimit', 'how many failed Jobs are kept around'],
] as const;

function checkHistoryLimits(ctx: RuleContext, spec: Record<string, unknown>): void {
  for (const [field, meaning] of HISTORY_LIMIT_FIELDS) {
    // Zero is a valid limit — it means "keep none" — so only a negative value
    // is rejected.
    const value = asNumber(spec[field]);
    if (value === undefined || value >= 0) continue;
    ctx.report({
      ruleId: 'cronjob/negative-history-limit',
      severity: 'error',
      path: ['spec', field],
      message: `${field} must not be negative, but is ${value}.`,
      explanation: `It is ${meaning}.`,
      docsUrl: CRONJOB_DOCS,
    });
  }
}

/* Name length */

function checkNameLength(ctx: RuleContext): void {
  const name = asString(asObject(ctx.doc['metadata'])?.['name']);
  // A name that is not even a valid object name is metadata.ts's to report.
  if (name === undefined || !isDNS1123Subdomain(name).ok) return;
  if (name.length <= CRONJOB_NAME_MAX) return;

  ctx.report({
    ruleId: 'cronjob/name-too-long',
    severity: 'error',
    path: ['metadata', 'name'],
    message: `A CronJob name must be at most ${CRONJOB_NAME_MAX} characters, but "${name}" is ${name.length}.`,
    explanation:
      'The CronJob controller appends "-<timestamp>", 11 characters, to this name to make each run\'s Job name, and a Job name has to fit in the 63-character limit a DNS label allows — so the CronJob\'s own name is capped at 63 - 11 rather than the usual 253.',
    docsUrl: CRONJOB_DOCS,
  });
}

/* Job template selector */

/**
 * Unlike a hand-written Job, whose selector can be written manually with
 * manualSelector: true, a CronJob's jobTemplate has no such escape hatch:
 * every Job it creates is fresh, never adopted, so the apiserver generates
 * the selector unconditionally and rejects either field outright.
 */
function checkJobTemplateSelector(ctx: RuleContext, jobSpec: Record<string, unknown>): void {
  if (jobSpec['selector'] !== undefined) {
    ctx.report({
      ruleId: 'cronjob/job-template-selector',
      severity: 'error',
      path: ['spec', 'jobTemplate', 'spec', 'selector'],
      anchor: 'key',
      message: "jobTemplate.spec.selector is generated by the apiserver and must not be set.",
      explanation:
        'Each Job this CronJob creates gets its own selector generated from that Job\'s UID, exactly as a hand-written Job\'s does. The apiserver rejects a selector here with "`selector` will be auto-generated".',
      docsUrl: CRONJOB_DOCS,
      fix: {
        title: 'Remove the selector',
        safe: false,
        ops: [{ op: 'delete', path: ['spec', 'jobTemplate', 'spec', 'selector'] }],
      },
    });
  }

  if (asBoolean(jobSpec['manualSelector']) === true) {
    ctx.report({
      ruleId: 'cronjob/job-template-manual-selector',
      severity: 'error',
      path: ['spec', 'jobTemplate', 'spec', 'manualSelector'],
      message: 'jobTemplate.spec.manualSelector must be false, or left out.',
      explanation:
        'manualSelector is a Job\'s way of adopting Pods something else already created; a CronJob\'s Jobs are always created fresh, so there is nothing to adopt and the apiserver accepts only "false" or an absent field here.',
      docsUrl: CRONJOB_DOCS,
      fix: {
        title: 'Remove manualSelector',
        safe: false,
        ops: [{ op: 'delete', path: ['spec', 'jobTemplate', 'spec', 'manualSelector'] }],
      },
    });
  }
}
